Various code cleanup and refactoring
- Ensure that the various VBOX_* variables are properly closed such that
  the arguments are properly formed.
- The various VBoxManage use cases have been encapsulated in various
  helpers for ease of access, or broken down into better managed pieces
  (wait_vm_shutdown)
- Provide the warn and die helpers, removed the reqstmt as the || or &&
  shorthands are better/more conventional of bash for representing what
  is being done on the condition of the statement.
- Added more test cases and fixtures where applicable.

diff --git a/bin/createvm-gentoo b/bin/createvm-gentoo
--- a/bin/createvm-gentoo
+++ b/bin/createvm-gentoo
@@ -4,51 +4,41 @@
 DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 source $DIR/../lib/gentoo
 
-create_vm gentoo
-if [ $? -ne 0 ]; then
-    echo "failed to create vm ${VBOX_NAME} for gentoo build"
-    exit 1
-fi
+create_vm gentoo || \
+    die "failed to create vm ${VBOX_NAME} for gentoo build"
 
-reqstmt checkenvfile GENTOO_STAGE3 GENTOO_PORTAGE
+checkenvfile GENTOO_STAGE3 GENTOO_PORTAGE || exit 1
 
 VBoxManage startvm "${VBOX_NAME}"
 prepare_gentoo_boot_iso
 
-scp -oStrictHostKeyChecking=no -oBatchMode=Yes -i $VBOX_PRIVKEY \
-    $GENTOO_STAGE3 root@$VBOX_IP:stage3-amd64.tar
+scp -oStrictHostKeyChecking=no -oBatchMode=Yes -i "${VBOX_PRIVKEY}" \
+    "${GENTOO_STAGE3}" root@$VBOX_IP:stage3-amd64.tar
 
-scp -oStrictHostKeyChecking=no -oBatchMode=Yes -i $VBOX_PRIVKEY \
-    $GENTOO_PORTAGE root@$VBOX_IP:portage.tar
+scp -oStrictHostKeyChecking=no -oBatchMode=Yes -i "${VBOX_PRIVKEY}" \
+    "${GENTOO_PORTAGE}" root@$VBOX_IP:portage.tar
 
-rsync -re "ssh -oStrictHostKeyChecking=no -oBatchMode=Yes -i $VBOX_PRIVKEY" \
-    $GENTOO_FILES/ root@$VBOX_IP:gentoo_files
+rsync -re \
+    "ssh -oStrictHostKeyChecking=no -oBatchMode=Yes -i \"${VBOX_PRIVKEY}\"" \
+    "${GENTOO_FILES}/" root@$VBOX_IP:gentoo_files
 
-# pass that as a stuff directly into the screen session
-ssh -oStrictHostKeyChecking=no -oBatchMode=Yes -i $VBOX_PRIVKEY root@$VBOX_IP \
-    ./gentoo_files/init.sh
+ssh -oStrictHostKeyChecking=no -oBatchMode=Yes -i "${VBOX_PRIVKEY}" \
+    root@$VBOX_IP ./gentoo_files/init.sh
 
 if [ $? -ne 0 ]; then
-    echo "error with installation"
-    wait_vm_shutdown "${VBOX_NAME}" 15
-    if [ $? -ne 0 ]; then
-        echo "\"${VBOX_NAME}\" failed to shutdown"
-    fi
+    warn "error with installation"
+    forcepoweroff_vm "${VBOX_NAME}" 15
     exit 1
 fi
 
-wait_vm_shutdown "${VBOX_NAME}" 15
-
-if [ $? -ne 0 ]; then
-    echo "\"${VBOX_NAME}\" did not shutdown; cannot continue with verification"
-    exit 1
-fi
+wait_vm_shutdown "${VBOX_NAME}" 15 || \
+    die "'${VBOX_NAME}' did not shutdown; cannot continue with verification"
 
 # remove the boot iso for proper bootup.
-VBoxManage storageattach $VBOX_NAME --storagectl IDE --port 0 --device 0 \
+VBoxManage storageattach "${VBOX_NAME}" --storagectl IDE --port 0 --device 0 \
     --medium emptydrive
 
 VBoxManage startvm "${VBOX_NAME}"
 echo "the vm may be accessible after it completes the booting process using:"
-echo "ssh -oStrictHostKeyChecking=no -oBatchMode=Yes -i $VBOX_PRIVKEY \
+echo "ssh -oStrictHostKeyChecking=no -oBatchMode=Yes -i \"${VBOX_PRIVKEY}\" \
     root@$VBOX_IP"
diff --git a/lib/utils b/lib/utils
--- a/lib/utils
+++ b/lib/utils
@@ -3,18 +3,20 @@
 
 DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 
-reqstmt () {
-    eval $@
-    if [ $? -ne 0 ]; then
-        exit 1
-    fi
+warn () {
+    echo $@ >&2
+}
+
+die () {
+    warn $@
+    exit 1
 }
 
 sourceconfigs () {
     for name in $@; do
         config=$DIR/../share/config/$name
-        if [ ! -f ${config} ]; then
-            echo "configfile '${config}' not found"
+        if [ ! -f "${config}" ]; then
+            warn "configfile '${config}' not found"
             return 1
         fi
         source $config
@@ -23,22 +25,18 @@ sourceconfigs () {
 
 checkenv () {
     for name in $@; do
-        if [ -z ${!name} ]; then
-            echo "${name} is undefined"
+        if [ -z "${!name}" ]; then
+            warn "'${name}' is undefined"
             return 1
         fi
     done
 }
 
 checkenvfile () {
-    checkenv $@
-    if [ ! $? -eq 0 ]; then
-        return 1
-    fi
-
+    checkenv $@ || return 1
     for name in $@; do
-        if [ ! -f ${!name} ]; then
-            echo "${!name} is missing in working directory; aborting"
+        if [ ! -f "${!name}" ]; then
+            warn "'${!name}' is missing in working directory; aborting"
             return 1
         fi
     done
@@ -49,18 +47,18 @@ putscancode () {
 }
 
 runscancode () {
-    target=${2:-$VBOX_NAME}
+    target=${2:-${VBOX_NAME}}
     default=${VBOX_SCANCODE_LIMIT-10}
     limit=${3-$default}
     putscancode $1 | xargs -n $limit \
-        VBoxManage controlvm "$target" keyboardputscancode
+        VBoxManage controlvm "${target}" keyboardputscancode
 }
 
 set_vm_mac_ip () {
     name=$1
     net=$2
     VBOX_MAC=$(
-        VBoxManage showvminfo ${name} | grep ${net} | \
+        VBoxManage showvminfo "${name}" | grep "${net}" | \
         sed -r 's/.*MAC: ([0-9A-F]*).*/\1/' | sed -r 's/(.{2})/:\1/g' | \
         cut -b 2-
     )
@@ -69,7 +67,7 @@ set_vm_mac_ip () {
         arp | grep -i ${VBOX_MAC} | cut -d' ' -f1
     )
     if [ -z $VBOX_IP ]; then
-        echo "failed to derive IP"
+        warn "failed to derive IP"
         return 1
     fi
     echo "ip is $VBOX_IP"
@@ -77,26 +75,47 @@ set_vm_mac_ip () {
     export VBOX_IP=$VBOX_IP
 }
 
+find_vm () {
+    name=$1
+    # provide the double quotes to ensure full string is matched against
+    # the double-quoted output.
+    VBoxManage list vms |grep "\"${name}\"" > /dev/null
+    if [ ! $? -eq 0 ]; then
+        warn "vm '${name}' not found"
+        return 1
+    fi
+}
+
+check_vm_running () {
+    name=$1
+    VBoxManage list runningvms |grep "\"${name}\"" > /dev/null
+}
+
 wait_vm_shutdown () {
     # wait for a vm to shutdown, default 10 seconds
-    name=\"$1\"
+    name=$1
     timeout=${2:-10}  # default 10 seconds timeout
-    VBoxManage list vms |grep "$name" > /dev/null
 
-    if [ ! $? -eq 0 ]; then
-        echo "vm $name not found"
-        return 2
-    fi
-
+    find_vm "${name}" || return 2
     for ((i=0; i <= $timeout; i++)) do
-        VBoxManage list runningvms |grep "$name" > /dev/null
-        if [ ! $? -eq 0 ]; then
-            return 0
-        fi
+        # return success code 0 if no longer running
+        check_vm_running "${name}" || return 0
         if [ $i -ne $timeout ]; then
             sleep 1
         fi
     done
+    # still running, so this has failed.
+    return 1
+}
+
+forcepoweroff_vm () {
+    name=$1
+    timeout=$2
+    # try to trigger an acpi shutdown for a more graceful shutdown first
+    VBoxManage controlvm "${name}" acpipowerbutton
+    wait_vm_shutdown "${name}" $timeout && return 0
+    warn "'${name}' failed to shutdown; forcing poweroff"
+    VBoxManage controlvm "${name}" poweroff
     return 1
 }
 
@@ -116,30 +135,27 @@ set_vm_environ () {
         return 1
     fi
 
-    export VBOX_HOME=$VBOX_ROOT/$VBOX_NAME
-    export VBOX_IMG=$VBOX_HOME/$VBOX_NAME.vhd
-    export VBOX_PRIVKEY=$VBOX_HOME/id_rsa
-    export VBOX_PUBKEY=$VBOX_HOME/id_rsa.pub
+    export VBOX_HOME="${VBOX_ROOT}/${VBOX_NAME}"
+    export VBOX_IMG="${VBOX_HOME}/${VBOX_NAME}.vhd"
+    export VBOX_PRIVKEY="${VBOX_HOME}/id_rsa"
+    export VBOX_PUBKEY="${VBOX_HOME}/id_rsa.pub"
     export VBOX_NET=vboxnet0
 }
 
 create_vm () {
     set_vm_environ $@ &&
-    checkenvfile BOOT_ISO
-    if [ ! $? -eq 0 ]; then
-        return 1
-    fi
+    checkenvfile BOOT_ISO || return 1
 
     # verify that the vm and image does not already exists yet
-    VBoxManage showvminfo $VBOX_NAME 2>/dev/null >/dev/null
+    VBoxManage showvminfo "${VBOX_NAME}" 2>/dev/null >/dev/null
     if [ $? -eq 0 ]; then
-        echo "'${VBOX_NAME}' is already registered as a vm"
-        echo "(unregister with: VBoxManage unregistervm '${VBOX_NAME}')"
+        warn "'${VBOX_NAME}' is already registered as a vm"
+        warn "(unregister with: VBoxManage unregistervm '${VBOX_NAME}')"
         return 1
     fi
 
     if [ -f "${VBOX_IMG}" ]; then
-        echo "vm image at '${VBOX_IMG}' already exists"
+        warn "vm image at '${VBOX_IMG}' already exists"
         return 1
     fi
 
@@ -151,41 +167,51 @@ create_vm () {
 
     # find the existence of the target vboxnet, which may not be present
     # (this is the reason for sticking with default $VBOX_NET)
-    VBoxManage list hostonlyifs |grep $VBOX_NET 2> /dev/null >/dev/null
+    VBoxManage list hostonlyifs |grep "${VBOX_NET}" 2> /dev/null >/dev/null
     if [ $? -ne 0 ]; then
-        echo "hostonlyif ${VBOX_NET} does not exist"
+        warn "hostonlyif ${VBOX_NET} does not exist"
         return 1
     fi
 
     export VBOX_HOST_IP=$(
-        VBoxManage list hostonlyifs |grep ${VBOX_NET} -A4 | \
+        VBoxManage list hostonlyifs |grep "${VBOX_NET}" -A4 | \
         grep IPAddress| awk '{print $2}'
     )
 
     # create the VM; end each command with &&
 
-    mkdir -p $VBOX_ROOT &&
-    VBoxManage createvm --name $VBOX_NAME --basefolder $VBOX_ROOT --register &&
-    VBoxManage modifyvm $VBOX_NAME --ostype Gentoo_64 --memory=4096 \
+    mkdir -p "${VBOX_ROOT}" &&
+    VBoxManage createvm --name "${VBOX_NAME}" --basefolder "${VBOX_ROOT}" \
+        --register &&
+    VBoxManage modifyvm "${VBOX_NAME}" --ostype Gentoo_64 --memory=4096 \
         --cpus $VBOX_N_CPU --ioapic on \
         --nic1 hostonly --nic2 nat --cableconnected1 on --cableconnected2 on \
-        --nictype1 82540EM --nictype2 82540EM --hostonlyadapter1 $VBOX_NET &&
+        --nictype1 82540EM --nictype2 82540EM \
+        --hostonlyadapter1 "${VBOX_NET}" &&
 
-    VBoxManage storagectl $VBOX_NAME --name IDE --add ide --controller PIIX4 &&
-    VBoxManage storagectl $VBOX_NAME --name SATA --add sata \
+    VBoxManage storagectl "${VBOX_NAME}" --name IDE --add ide \
+        --controller PIIX4 &&
+    VBoxManage storagectl "${VBOX_NAME}" --name SATA --add sata \
         --controller IntelAhci --portcount 4 &&
 
     VBoxManage createmedium disk --size $VBOX_DISK_SIZE --format VHD \
-        --filename $VBOX_IMG &&
+        --filename "${VBOX_IMG}" &&
 
-    VBoxManage storageattach $VBOX_NAME --storagectl IDE --port 0 --device 0 \
-        --type dvddrive --medium $BOOT_ISO &&
-    VBoxManage storageattach $VBOX_NAME --storagectl SATA --port 0 --device 0 \
-        --type hdd --medium $VBOX_IMG &&
+    VBoxManage storageattach "${VBOX_NAME}" --storagectl IDE --port 0 \
+        --device 0 --type dvddrive --medium "${BOOT_ISO}" &&
+    VBoxManage storageattach "${VBOX_NAME}" --storagectl SATA --port 0 \
+        --device 0 --type hdd --medium "${VBOX_IMG}" &&
 
     # generate ssh keys
-    ssh-keygen -N '' -C $VBOX_NAME -f $VBOX_PRIVKEY &&
+    ssh-keygen -N '' -C "${VBOX_NAME}" -f "${VBOX_PRIVKEY}" &&
 
     # finalize it with true to stop the last &&
     true
+}
+
+connect_vm () {
+    set_vm_environ $@
+    set_vm_mac_ip
+    ssh -oStrictHostKeyChecking=no -oBatchMode=Yes -i "${VBOX_PRIVKEY}" \
+        root@${VBOX_IP}
 }
