Simplify the startup
- Have the execution done inline in this current console with all output
  captured here, so screen is no longer needed.
- Also wait for the shutdown for boot iso media removal.

diff --git a/bin/createvm-gentoo b/bin/createvm-gentoo
--- a/bin/createvm-gentoo
+++ b/bin/createvm-gentoo
@@ -34,7 +34,7 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-start_vm
+VBoxManage startvm "${VBOX_NAME}"
 
 # hit enter a couple times
 # first to boot from the iso.
@@ -57,7 +57,6 @@ if [ $? -ne 0 ]; then
 fi
 
 # run everything in a screen session
-runscancode "screen"
 runscancode "/etc/init.d/sshd start"
 runscancode "mkdir ~/.ssh"
 runscancode "echo $(cat $VBOX_PUBKEY) > ~/.ssh/authorized_keys"
@@ -73,4 +72,20 @@ rsync -re "ssh -oStrictHostKeyChecking=no -oBatchMode=Yes -i $VBOX_PRIVKEY" \
 
 # pass that as a stuff directly into the screen session
 ssh -oStrictHostKeyChecking=no -oBatchMode=Yes -i $VBOX_PRIVKEY root@$VBOX_IP \
-    "screen -p 0 -X stuff './gentoo_files/init.sh^m'"
+    ./gentoo_files/init.sh
+
+wait_vm_shutdown "${VBOX_NAME}" 15
+
+if [ $? -ne 0 ]; then
+    echo "\"${VBOX_NAME}\" did not shutdown; cannot continue with verification"
+    exit 1
+fi
+
+# remove the boot iso for proper bootup.
+VBoxManage storageattach $VBOX_NAME --storagectl IDE --port 0 --device 0 \
+    --medium emptydrive
+
+VBoxManage startvm "${VBOX_NAME}"
+echo "the vm may be accessible after it completes the booting process using:"
+echo "ssh -oStrictHostKeyChecking=no -oBatchMode=Yes -i $VBOX_PRIVKEY \
+    root@$VBOX_IP"
diff --git a/lib/utils b/lib/utils
--- a/lib/utils
+++ b/lib/utils
@@ -51,6 +51,29 @@ set_vm_mac_ip () {
     export VBOX_IP=$VBOX_IP
 }
 
+wait_vm_shutdown () {
+    # wait for a vm to shutdown, default 10 seconds
+    name=\"$1\"
+    timeout=${2:-10}  # default 10 seconds timeout
+    VBoxManage list vms |grep "$name" > /dev/null
+
+    if [ ! $? -eq 0 ]; then
+        echo "vm $name not found"
+        return 2
+    fi
+
+    for ((i=0; i <= $timeout; i++)) do
+        VBoxManage list runningvms |grep "$name" > /dev/null
+        if [ ! $? -eq 0 ]; then
+            return 0
+        fi
+        if [ $i -ne $timeout ]; then
+            sleep 1
+        fi
+    done
+    return 1
+}
+
 create_vm () {
     checkenv BOOT_ISO VBOX_NAME
     if [ ! $? -eq 0 ]; then
@@ -122,9 +145,4 @@ create_vm () {
 
     # finalize it with true to stop the last &&
     true
-}
-
-start_vm () {
-    # boot VM
-    VBoxManage startvm $VBOX_NAME
 }
