Organizing as a library and executable.
- Done inside standard directory names for the respective purposes.
- Clean up various trial code and replace them with more standardized
  call conventions.
- Also ensure that the VM creation command fails faster.

diff --git a/lib/utils b/lib/utils
--- a/lib/utils
+++ b/lib/utils
@@ -1,10 +1,28 @@
 #!/bin/bash
 # change these settings to a more suitable form
 
-. ./env.sh
+DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
+
+checkenv () {
+    for name in $@; do
+        if [ -z ${!name} ]; then
+            echo "${name} is undefined"
+            return 1
+        fi
+    done
+}
+
+checkenvfile () {
+    for name in $@; do
+        if [ ! -f ${!name} ]; then
+            echo "${!name} is missing in working directory; aborting"
+            return 1
+        fi
+    done
+}
 
 putscancode () {
-    echo $@ | python scancode.py
+    echo $@ | $DIR/../bin/scancode.py
 }
 
 runscancode () {
@@ -26,24 +44,19 @@ set_vm_mac_ip () {
     )
     if [ -z $VBOX_IP ]; then
         echo "failed to derive IP, cannot continue with automated installation"
-        false
-        return
+        return 1
     fi
     echo "ip is $VBOX_IP"
     export VBOX_MAC=$VBOX_MAC
     export VBOX_IP=$VBOX_IP
 }
 
-# don't provide the vm functions until things are defined
-for name in BOOT_ISO VBOX_NAME; do
-    if [ -z ${!name} ]; then
-        echo "${name} is undefined"
-        false
-        return
-    fi
-done
-
 create_vm () {
+    checkenv BOOT_ISO VBOX_NAME
+    if [ ! $? -eq 0 ]; then
+        return 1
+    fi
+
     # standard settings, modify with care
     export VBOX_HOME=$VBOX_ROOT/$VBOX_NAME
     export VBOX_IMG=$VBOX_HOME/$VBOX_NAME.vhd
@@ -56,14 +69,12 @@ create_vm () {
     if [ $? -eq 0 ]; then
         echo "'${VBOX_NAME}' is already registered as a vm"
         echo "(unregister with: VBoxManage unregistervm '${VBOX_NAME}')"
-        false
-        return
+        return 1
     fi
 
     if [ -f "${VBOX_IMG}" ]; then
         echo "vm image at '${VBOX_IMG}' already exists"
-        false
-        return
+        return 1
     fi
 
     # automatically create vboxnet0 if not exists
@@ -77,8 +88,7 @@ create_vm () {
     VBoxManage list hostonlyifs |grep $VBOX_NET 2> /dev/null >/dev/null
     if [ $? -ne 0 ]; then
         echo "hostonlyif ${VBOX_NET} does not exist"
-        false
-        return
+        return 1
     fi
 
     export VBOX_HOST_IP=$(
@@ -86,31 +96,33 @@ create_vm () {
         grep IPAddress| awk '{print $2}'
     )
 
-    # create the VM
+    # create the VM; end each command with &&
 
-    mkdir -p $VBOX_ROOT
-    VBoxManage createvm --name $VBOX_NAME --basefolder $VBOX_ROOT --register
+    mkdir -p $VBOX_ROOT &&
+    VBoxManage createvm --name $VBOX_NAME --basefolder $VBOX_ROOT --register &&
     VBoxManage modifyvm $VBOX_NAME --ostype Gentoo_64 --memory=4096 \
         --cpus $VBOX_N_CPU --ioapic on \
         --nic1 hostonly --nic2 nat --cableconnected1 on --cableconnected2 on \
-        --nictype1 82540EM --nictype2 82540EM --hostonlyadapter1 $VBOX_NET
+        --nictype1 82540EM --nictype2 82540EM --hostonlyadapter1 $VBOX_NET &&
 
-    VBoxManage storagectl $VBOX_NAME --name IDE --add ide --controller PIIX4
+    VBoxManage storagectl $VBOX_NAME --name IDE --add ide --controller PIIX4 &&
     VBoxManage storagectl $VBOX_NAME --name SATA --add sata \
-        --controller IntelAhci --portcount 4
+        --controller IntelAhci --portcount 4 &&
 
     VBoxManage createmedium disk --size $VBOX_DISK_SIZE --format VHD \
-        --filename $VBOX_IMG
+        --filename $VBOX_IMG &&
 
     VBoxManage storageattach $VBOX_NAME --storagectl IDE --port 0 --device 0 \
-        --type dvddrive --medium $BOOT_ISO
+        --type dvddrive --medium $BOOT_ISO &&
     VBoxManage storageattach $VBOX_NAME --storagectl SATA --port 0 --device 0 \
-        --type hdd --medium $VBOX_IMG
+        --type hdd --medium $VBOX_IMG &&
 
     # generate ssh keys
-    ssh-keygen -N '' -f $VBOX_PRIVKEY
-}
+    ssh-keygen -N '' -C $VBOX_NAME -f $VBOX_PRIVKEY &&
 
+    # finalize it with true to stop the last &&
+    true
+}
 
 start_vm () {
     # boot VM
